### ISSUE TITLE
Import buttons disabled on bulk uploader page

### ISSUE THREAD

**Issue by dboyer** [OpenTreeMap/OTM2#1938]
This is on production. The buttons are disabled both before and after I browse and select a file to upload.

This is on both existing maps and a new map I just created.

**Comment by jwalgran** [comment]
@dboyer I was able to reproduce this, and resolve it. The problem is with cached javascript. Force reloading the page will "fix" the the button.

**Comment by dboyer** [comment]
Ugh, amateur mistake on my end. Sorry about that.

**Comment by maurizi** [comment]
This is a symptom of a larger problem though.
Our users will not think to and shouldn't *have* to clear their cache in order to be able to use our site.

We should add some sort of cache invalidation so that when we update production users will automatically get new JS files, without having to clear their browser cache.

I've added an issue for it here: #1939
